import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/molecules/navbar";
import Home from "./page";
import { montserrat } from "./font";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiadased`} style={{scrollBehavior:'smooth'}}>
        <Navbar/>
        <Home/>
      </body>
    </html>
  );
}
